#pragma once

#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_FORCE_HOLD_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT

/* endgame mod tap settings https://github.com/manna-harbour/qmk_firmware/pull/56 */
#define BILATERAL_COMBINATIONS
#define BILATERAL_COMBINATIONS_ALLOW_SAMESIDED_AFTER 300
#define BILATERAL_COMBINATIONS_ALLOW_CROSSOVER_AFTER 1
//#define BILATERAL_COMBINATIONS_DELAY_MODS_THAT_MATCH MOD_MASK_GUI // (MOD_MASK_GUI|MOD_MASK_ALT) // GUI and ALT modifiers
//#define BILATERAL_COMBINATIONS_DELAY_MATCHED_MODS_BY 100
#define BILATERAL_COMBINATIONS_TYPING_STREAK_TIMEOUT 175
#define BILATERAL_COMBINATIONS_TYPING_STREAK_MODMASK (~MOD_MASK_SHIFT)

