#pragma once

#define VIAL_KEYBOARD_UID {0xB0, 0x1D, 0x46, 0xC8, 0xD2, 0x92, 0x7F, 0x1C}

#define VIAL_UNLOCK_COMBO_ROWS { 1, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 16

/* endgame mod tap settings https://github.com/manna-harbour/qmk_firmware/pull/56 */
#define BILATERAL_COMBINATIONS
#define BILATERAL_COMBINATIONS_ALLOW_SAMESIDED_AFTER 300
#define BILATERAL_COMBINATIONS_ALLOW_CROSSOVER_AFTER 1
//#define BILATERAL_COMBINATIONS_DELAY_MODS_THAT_MATCH MOD_MASK_GUI // (MOD_MASK_GUI|MOD_MASK_ALT) // GUI and ALT modifiers
//#define BILATERAL_COMBINATIONS_DELAY_MATCHED_MODS_BY 100
#define BILATERAL_COMBINATIONS_TYPING_STREAK_TIMEOUT 175
#define BILATERAL_COMBINATIONS_TYPING_STREAK_MODMASK (~MOD_MASK_SHIFT)

