# Split keyboard
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

# OLED
OLED_ENABLE = yes
OLED_DRIVER = ssd1306

# Other
CAPS_WORD_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
SWAP_HANDS_ENABLE = yes
APPLE_FN_ENABLE = yes
